export const vacancies = [
  {
    id: 1,
    title: "Менеджер по продажам",
    description:
      "Активные продажи и расширение клиентской базы. Работа с возражениями.",
    status: "Активна",
    createdById: 101,
    createdAt: "2024-03-15T09:30:00Z",
    IsDeleted: false,
  },
  {
    id: 2,
    title: "Frontend-разработчик",
    description: "Разработка интерфейсов на React. Опыт от 2-х лет.",
    status: "Активна",
    createdById: 102,
    createdAt: "2024-03-16T10:15:00Z",
    IsDeleted: false,
  },
  {
    id: 3,
    title: "Бухгалтер",
    description: "Ведение первичной документации, расчет заработной платы.",
    status: "В архиве",
    createdById: 103,
    createdAt: "2024-02-10T14:20:00Z",
  },
  {
    id: 4,
    title: "Системный администратор",
    description: "Поддержка пользователей, настройка ПО и оборудования.",
    status: "Активна",
    createdById: 104,
    createdAt: "2024-03-14T11:45:00Z",
    IsDeleted: false,
  },
  {
    id: 5,
    title: "Маркетолог",
    description: "SEO-продвижение, SMM, контекстная реклама.",
    status: "Черновик",
    createdById: 105,
    createdAt: "2024-03-10T08:30:00Z",
    IsDeleted: false,
  },
  {
    id: 6,
    title: "Водитель-экспедитор",
    description: "Категория B, стаж от 3-х лет. Развоз товаров по городу.",
    status: "Активна",
    createdById: 106,
    createdAt: "2024-03-17T13:20:00Z",
    IsDeleted: false,
  },
  {
    id: 7,
    title: "Backend-разработчик",
    description: "Node.js, Python. Разработка API и серверной логики.",
    status: "Активна",
    createdById: 107,
    createdAt: "2024-03-12T09:45:00Z",
    IsDeleted: false,
  },
  {
    id: 8,
    title: "Офис-менеджер",
    description:
      "Организация документооборота, встреча гостей, заказ канцелярии.",
    status: "Закрыта",
    createdById: 108,
    createdAt: "2024-01-25T10:00:00Z",
    IsDeleted: false,
  },
  {
    id: 9,
    title: "Грузчик",
    description: "Физическая работа, сменный график.",
    status: "Активна",
    createdById: 109,
    createdAt: "2024-03-16T15:10:00Z",
    IsDeleted: false,
  },
  {
    id: 10,
    title: "HR-менеджер",
    description:
      "Поиск и подбор персонала, собеседования, адаптация сотрудников.",
    status: "Активна",
    createdById: 110,
    createdAt: "2024-03-13T12:30:00Z",
    IsDeleted: false,
  },
  {
    id: 11,
    title: "UI/UX дизайнер",
    description: "Проектирование интерфейсов, создание прототипов и макетов.",
    status: "Черновик",
    createdById: 111,
    createdAt: "2024-03-09T11:20:00Z",
    IsDeleted: false,
  },
  {
    id: 12,
    title: "Курьер",
    description: "Доставка документов и товаров по городу. Гибкий график.",
    status: "Активна",
    createdById: 112,
    createdAt: "2024-03-18T09:00:00Z",
    IsDeleted: false,
  },
  {
    id: 13,
    title: "Тестировщик QA",
    description:
      "Ручное тестирование веб-приложений, составление баг-репортов.",
    status: "В архиве",
    createdById: 113,
    createdAt: "2024-02-28T14:40:00Z",
  },
  {
    id: 14,
    title: "Юрист",
    description:
      "Консультирование, договорная работа, претензионная деятельность.",
    status: "Активна",
    createdById: 114,
    createdAt: "2024-03-14T16:15:00Z",
    IsDeleted: false,
  },
  {
    id: 15,
    title: "Уборщица",
    description: "Уборка офисных помещений, 3 раза в неделю.",
    status: "Активна",
    createdById: 115,
    createdAt: "2024-03-17T10:30:00Z",
    IsDeleted: false,
  },
];

export const vacancyApplications = {
  1: [
    {
      id: 101,
      firstName: "Алексей",
      lastName: "Смирнов",
      email: "a.smirnov@example.com",
      phone: "+7 (916) 123-45-67",
      stage: "Новый",
      createdBy: "Елена Петрова",
      resumeFileUrl: "",
      resumeName: "Смирнов_Алексей_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 102,
      firstName: "Дмитрий",
      lastName: "Козлов",
      email: "d.kozlov@example.com",
      phone: "+7 (925) 234-56-78",
      stage: "Телефонное интервью",
      createdBy: "Елена Петрова",
      resumeFileUrl: "",
      resumeName: "Козлов_Дмитрий_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 103,
      firstName: "Иван",
      lastName: "Морозов",
      email: "i.morozov@example.com",
      phone: null,
      stage: "Отказ",
      createdBy: "Михаил Сидоров",
      resumeFileUrl: "",
      resumeName: "Морозов_Иван_резюме.pdf",
      isDeleted: true,
    },
  ],

  2: [
    {
      id: 201,
      firstName: "Екатерина",
      lastName: "Волкова",
      email: "e.volkova@example.com",
      phone: "+7 (903) 345-67-89",
      stage: "Техническое собеседование",
      createdBy: "Анна Иванова",
      resumeFileUrl: "",
      resumeName: "Волкова_Екатерина_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 202,
      firstName: "Павел",
      lastName: "Соколов",
      email: "p.sokolov@example.com",
      phone: "+7 (915) 456-78-90",
      stage: "Новый",
      createdBy: "Анна Иванова",
      resumeFileUrl: "",
      resumeName: "Соколов_Павел_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 203,
      firstName: "Артем",
      lastName: "Михайлов",
      email: "a.mikhailov@example.com",
      phone: "+7 (926) 567-89-01",
      stage: "Тестовое задание",
      createdBy: "Дмитрий Орлов",
      resumeFileUrl: "",
      resumeName: "Михайлов_Артем_резюме.pdf",
      isDeleted: false,
    },
  ],

  3: [
    {
      id: 301,
      firstName: "Ольга",
      lastName: "Новикова",
      email: "o.novikova@example.com",
      phone: "+7 (985) 678-90-12",
      stage: "Новый",
      createdBy: "Светлана Козлова",
      resumeFileUrl: "",
      resumeName: "Новикова_Ольга_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 302,
      firstName: "Наталья",
      lastName: "Федорова",
      email: "n.fedorova@example.com",
      phone: "+7 (916) 789-01-23",
      stage: "Оценка",
      createdBy: "Светлана Козлова",
      resumeFileUrl: "",
      resumeName: "Федорова_Наталья_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 303,
      firstName: "Татьяна",
      lastName: "Алексеева",
      email: "t.alekseeva@example.com",
      phone: null,
      stage: "Отказ",
      createdBy: "Игорь Павлов",
      resumeFileUrl: "",
      resumeName: "Алексеева_Татьяна_резюме.pdf",
      isDeleted: true,
    },
  ],

  4: [
    {
      id: 401,
      firstName: "Максим",
      lastName: "Лебедев",
      email: "m.lebedev@example.com",
      phone: "+7 (903) 890-12-34",
      stage: "Техническое собеседование",
      createdBy: "Константин Смирнов",
      resumeFileUrl: "",
      resumeName: "Лебедев_Максим_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 402,
      firstName: "Андрей",
      lastName: "Ковалев",
      email: "a.kovalev@example.com",
      phone: "+7 (925) 901-23-45",
      stage: "Новый",
      createdBy: "Константин Смирнов",
      resumeFileUrl: "",
      resumeName: "Ковалев_Андрей_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 403,
      firstName: "Виктор",
      lastName: "Павлов",
      email: "v.pavlov@example.com",
      phone: "+7 (915) 012-34-56",
      stage: "Оффер",
      createdBy: "Елена Новикова",
      resumeFileUrl: "",
      resumeName: "Павлов_Виктор_резюме.pdf",
      isDeleted: false,
    },
  ],

  5: [
    {
      id: 501,
      firstName: "Ксения",
      lastName: "Семенова",
      email: "k.semenova@example.com",
      phone: "+7 (926) 123-45-67",
      stage: "Новый",
      createdBy: "Анастасия Григорьева",
      resumeFileUrl: "",
      resumeName: "Семенова_Ксения_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 502,
      firstName: "Юлия",
      lastName: "Зайцева",
      email: "y.zaytseva@example.com",
      phone: "+7 (985) 234-56-78",
      stage: "Портфолио",
      createdBy: "Анастасия Григорьева",
      resumeFileUrl: "",
      resumeName: "Зайцева_Юлия_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 503,
      firstName: "Алина",
      lastName: "Белова",
      email: "a.belova@example.com",
      phone: "+7 (916) 345-67-89",
      stage: "Тестовое задание",
      createdBy: "Максим Тарасов",
      resumeFileUrl: "",
      resumeName: "Белова_Алина_резюме.pdf",
      isDeleted: false,
    },
  ],

  6: [
    {
      id: 601,
      firstName: "Сергей",
      lastName: "Васильев",
      email: "s.vasiliev@example.com",
      phone: "+7 (903) 456-78-90",
      stage: "Новый",
      createdBy: "Николай Федоров",
      resumeFileUrl: "",
      resumeName: "Васильев_Сергей_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 602,
      firstName: "Александр",
      lastName: "Григорьев",
      email: "a.grigoriev@example.com",
      phone: "+7 (925) 567-89-01",
      stage: "Собеседование",
      createdBy: "Николай Федоров",
      resumeFileUrl: "",
      resumeName: "Григорьев_Александр_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 603,
      firstName: "Владимир",
      lastName: "Тимофеев",
      email: "v.timofeev@example.com",
      phone: "+7 (915) 678-90-12",
      stage: "Отказ",
      createdBy: "Ольга Соколова",
      resumeFileUrl: "",
      resumeName: "Тимофеев_Владимир_резюме.pdf",
      isDeleted: true,
    },
  ],

  7: [
    {
      id: 701,
      firstName: "Илья",
      lastName: "Орлов",
      email: "i.orlov@example.com",
      phone: "+7 (926) 789-01-23",
      stage: "Техническое собеседование",
      createdBy: "Татьяна Морозова",
      resumeFileUrl: "",
      resumeName: "Орлов_Илья_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 702,
      firstName: "Денис",
      lastName: "Макаров",
      email: "d.makarov@example.com",
      phone: "+7 (985) 890-12-34",
      stage: "Новый",
      createdBy: "Татьяна Морозова",
      resumeFileUrl: "",
      resumeName: "Макаров_Денис_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 703,
      firstName: "Глеб",
      lastName: "Никитин",
      email: "g.nikitin@example.com",
      phone: "+7 (916) 901-23-45",
      stage: "Финальное интервью",
      createdBy: "Алексей Воробьев",
      resumeFileUrl: "",
      resumeName: "Никитин_Глеб_резюме.pdf",
      isDeleted: false,
    },
  ],

  8: [
    {
      id: 801,
      firstName: "Анна",
      lastName: "Степанова",
      email: "a.stepanova@example.com",
      phone: "+7 (903) 012-34-56",
      stage: "Новый",
      createdBy: "Екатерина Белова",
      resumeFileUrl: "",
      resumeName: "Степанова_Анна_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 802,
      firstName: "Марина",
      lastName: "Ильина",
      email: "m.ilina@example.com",
      phone: "+7 (925) 123-45-67",
      stage: "Собеседование",
      createdBy: "Екатерина Белова",
      resumeFileUrl: "",
      resumeName: "Ильина_Марина_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 803,
      firstName: "Виктория",
      lastName: "Кузьмина",
      email: "v.kuzmina@example.com",
      phone: null,
      stage: "Отказ",
      createdBy: "Дмитрий Соловьев",
      resumeFileUrl: "",
      resumeName: "Кузьмина_Виктория_резюме.pdf",
      isDeleted: true,
    },
  ],

  9: [
    {
      id: 901,
      firstName: "Николай",
      lastName: "Петров",
      email: "n.petrov@example.com",
      phone: "+7 (915) 234-56-78",
      stage: "Новый",
      createdBy: "Александр Крылов",
      resumeFileUrl: "",
      resumeName: "Петров_Николай_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 902,
      firstName: "Роман",
      lastName: "Сидоров",
      email: "r.sidorov@example.com",
      phone: "+7 (926) 345-67-89",
      stage: "Оценка",
      createdBy: "Александр Крылов",
      resumeFileUrl: "",
      resumeName: "Сидоров_Роман_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 903,
      firstName: "Станислав",
      lastName: "Егоров",
      email: "s.egorov@example.com",
      phone: "+7 (985) 456-78-90",
      stage: "Отказ",
      createdBy: "Ирина Фомина",
      resumeFileUrl: "",
      resumeName: "Егоров_Станислав_резюме.pdf",
      isDeleted: false,
    },
  ],

  10: [
    {
      id: 1001,
      firstName: "Евгения",
      lastName: "Крылова",
      email: "e.krylova@example.com",
      phone: "+7 (916) 567-89-01",
      stage: "Новый",
      createdBy: "Вера Николаева",
      resumeFileUrl: "",
      resumeName: "Крылова_Евгения_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 1002,
      firstName: "Светлана",
      lastName: "Андреева",
      email: "s.andreeva@example.com",
      phone: "+7 (903) 678-90-12",
      stage: "Собеседование",
      createdBy: "Вера Николаева",
      resumeFileUrl: "",
      resumeName: "Андреева_Светлана_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 1003,
      firstName: "Дарья",
      lastName: "Герасимова",
      email: "d.gerasimova@example.com",
      phone: "+7 (925) 789-01-23",
      stage: "Оффер",
      createdBy: "Павел Гришин",
      resumeFileUrl: "",
      resumeName: "Герасимова_Дарья_резюме.pdf",
      isDeleted: false,
    },
  ],

  11: [
    {
      id: 1101,
      firstName: "Владислав",
      lastName: "Зуев",
      email: "v.zuev@example.com",
      phone: "+7 (915) 890-12-34",
      stage: "Портфолио",
      createdBy: "Мария Титова",
      resumeFileUrl: "",
      resumeName: "Зуев_Владислав_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 1102,
      firstName: "Кирилл",
      lastName: "Борисов",
      email: "k.borisov@example.com",
      phone: "+7 (926) 901-23-45",
      stage: "Новый",
      createdBy: "Мария Титова",
      resumeFileUrl: "",
      resumeName: "Борисов_Кирилл_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 1103,
      firstName: "Олег",
      lastName: "Фомин",
      email: "o.fomin@example.com",
      phone: null,
      stage: "Тестовое задание",
      createdBy: "Антон Кузнецов",
      resumeFileUrl: "",
      resumeName: "Фомин_Олег_резюме.pdf",
      isDeleted: false,
    },
  ],

  12: [
    {
      id: 1201,
      firstName: "Максим",
      lastName: "Беляков",
      email: "m.belyakov@example.com",
      phone: "+7 (985) 012-34-56",
      stage: "Новый",
      createdBy: "Надежда Сорокина",
      resumeFileUrl: "",
      resumeName: "Беляков_Максим_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 1202,
      firstName: "Арсений",
      lastName: "Денисов",
      email: "a.denisov@example.com",
      phone: "+7 (916) 123-45-67",
      stage: "Собеседование",
      createdBy: "Надежда Сорокина",
      resumeFileUrl: "",
      resumeName: "Денисов_Арсений_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 1203,
      firstName: "Тимофей",
      lastName: "Киселев",
      email: "t.kiselev@example.com",
      phone: "+7 (903) 234-56-78",
      stage: "Отказ",
      createdBy: "Григорий Миронов",
      resumeFileUrl: "",
      resumeName: "Киселев_Тимофей_резюме.pdf",
      isDeleted: true,
    },
  ],

  13: [
    {
      id: 1301,
      firstName: "Виталий",
      lastName: "Савельев",
      email: "v.saveliev@example.com",
      phone: "+7 (925) 345-67-89",
      stage: "Новый",
      createdBy: "Лариса Ершова",
      resumeFileUrl: "",
      resumeName: "Савельев_Виталий_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 1302,
      firstName: "Руслан",
      lastName: "Харитонов",
      email: "r.kharitonov@example.com",
      phone: "+7 (915) 456-78-90",
      stage: "Техническое собеседование",
      createdBy: "Лариса Ершова",
      resumeFileUrl: "",
      resumeName: "Харитонов_Руслан_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 1303,
      firstName: "Борис",
      lastName: "Шестаков",
      email: "b.shestakov@example.com",
      phone: "+7 (926) 567-89-01",
      stage: "Оценка",
      createdBy: "Валентин Романов",
      resumeFileUrl: "",
      resumeName: "Шестаков_Борис_резюме.pdf",
      isDeleted: false,
    },
  ],

  14: [
    {
      id: 1401,
      firstName: "Людмила",
      lastName: "Коновалова",
      email: "l.konovalova@example.com",
      phone: "+7 (985) 678-90-12",
      stage: "Новый",
      createdBy: "Зоя Филиппова",
      resumeFileUrl: "",
      resumeName: "Коновалова_Людмила_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 1402,
      firstName: "Галина",
      lastName: "Мельникова",
      email: "g.melnikova@example.com",
      phone: "+7 (916) 789-01-23",
      stage: "Собеседование",
      createdBy: "Зоя Филиппова",
      resumeFileUrl: "",
      resumeName: "Мельникова_Галина_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 1403,
      firstName: "Валентина",
      lastName: "Абрамова",
      email: "v.abramova@example.com",
      phone: null,
      stage: "Отказ",
      createdBy: "Степан Давыдов",
      resumeFileUrl: "",
      resumeName: "Абрамова_Валентина_резюме.pdf",
      isDeleted: true,
    },
  ],

  15: [
    {
      id: 1501,
      firstName: "Тамара",
      lastName: "Калинина",
      email: "t.kalinina@example.com",
      phone: "+7 (903) 890-12-34",
      stage: "Новый",
      createdBy: "Раиса Гусева",
      resumeFileUrl: "",
      resumeName: "Калинина_Тамара_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 1502,
      firstName: "Зинаида",
      lastName: "Сергеева",
      email: "z.sergeeva@example.com",
      phone: "+7 (925) 901-23-45",
      stage: "Оценка",
      createdBy: "Раиса Гусева",
      resumeFileUrl: "",
      resumeName: "Сергеева_Зинаида_резюме.pdf",
      isDeleted: false,
    },
    {
      id: 1503,
      firstName: "Нина",
      lastName: "Яковлева",
      email: "n.yakovleva@example.com",
      phone: "+7 (915) 012-34-56",
      stage: "Отказ",
      createdBy: "Федор Емельянов",
      resumeFileUrl: "",
      resumeName: "Яковлева_Нина_резюме.pdf",
      isDeleted: false,
    },
  ],
};
